{% set name = "circus" %}
{% set version = "0.17.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7e15dd1ef94f06e1aa00ac0dabe05b9e312633a7e58fa5e2361459e7f915f4c5

build:
  number: 3
  entry_points:
    - circusd = circus.circusd:main
    - circusd-stats = circus.stats:main
    - circusctl = circus.circusctl:main
    - circus-top = circus.stats.client:main
    - circus-plugin = circus.plugins:main
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  skip: true  # [win]

requirements:
  host:
    - python
    - pip
  run:
    - python
    - psutil
    - pyzmq >=17.0
    - tornado >=5.0.2

test:
  imports:
    - circus
    - circus.commands
    - circus.green
    - circus.plugins
    - circus.stats
    - circus.stream
    - circus.tests
  commands:
    - circusd --help
    - circusd-stats --help
    - circusctl --help
    - circus-top --help
    - circus-plugin --help

about:
  home: https://github.com/circus-tent/circus
  license: Apache-2.0
  license_file: LICENSE
  summary: Circus is a program that will let you run and watch multiple processes and sockets.

extra:
  recipe-maintainers:
    - vamega
    - carlodri
    - ltalirz
    - chrisjsewell
