{% set name = "circus" %}
{% set version = "0.16.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: dd7c011eb67785a1c96a4db94a56a22810c6ed608cebf301152dabc771654c5d

build:
  number: 2
  entry_points:
    - circusd = circus.circusd:main
    - circusd-stats = circus.stats:main
    - circusctl = circus.circusctl:main
    - circus-top = circus.stats.client:main
    - circus-plugin = circus.plugins:main
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  skip: True  # [win]

requirements:
  host:
    - python
    - pip
  run:
    - python
    - six
    - psutil
    - pyzmq >=17.0
    - tornado >=3.0,<5.0

test:
  imports:
    - circus
    - circus.commands
    - circus.green
    - circus.plugins
    - circus.stats
    - circus.stream
    - circus.tests
  commands:
    - circusd --help
    - circusd-stats --help
    - circusctl --help
    - circus-top --help
    - circus-plugin --help

about:
  home: https://github.com/circus-tent/circus
  license: Apache-2.0
  license_file: LICENSE
  summary: Circus is a program that will let you run and watch multiple processes and sockets.

extra:
  recipe-maintainers:
    - vamega
    - carlodri
    - ltalirz
    - chrisjsewell
