# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.
# -*- mode: yaml -*-

language: generic

os: osx
osx_image: xcode9.4


env:
  matrix:
    - CONFIG=osx_python2.7
    - CONFIG=osx_python3.6

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "Tkr3Y2a3T+JPTGxsBE0qLGV77lsk//Oz+M38O7JgNRxAmT6JgR/s0dRbauaf+NjS5Fa9lxU1/TtDDeU3/iAkmhod7nWZFneDIg2CKrwWXZntAIzN9rasFSwb/cqIr0CmLtx82Eiz3HD+aJC0GWbAJ6d/XRf9Gwljs1Lp+yVuJLGCQWSX3hBGumJ/EZY5ru81oDVCYLnFsBwad8/wkQnKaH+xwn6w1KPyT4dwW+oP9ASdhEy80DL9pwmYPm8PGzZiarDu7ssYePbv2/TYTYp/9MlQzsC+YoeKjPqoUEhGo+752S4n9qVGC0zJHqkMJQ72t0A1wUw/Lyfq7HZJRWhcGp0/yCc4eUaIEaxKRq9qqaWTSCiytowsiYlIM+7f1mnPnAX3/1B2cerHOM9PWYxC++klRMsX7yiv2lj93HX8UHDrgJu5tLxIa/aZnsFyTEBCIBP/mNMIr8pZL/y8Uk0m6ZDUCAd0ypxSNG2dhgri8qSC40EYTkumOufVNf21K0IJyR+ypou85OlWwlTliGnVWDD42gvcCmQwHLzlg1ZWjOGd3zuVD6IVUf0dYRTnHqExR1yP8kyKhnJg9AhU7dIxXzirc9mObqRWPXbRfEfhW5gJGiC3Pe90sNBsyyLNe9iOsao11xwS0MCiMdrD/AkhHmCvMSFdc4egELqTQtlKT3U="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/master/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install -n root -c conda-forge --quiet --yes conda-forge-ci-setup=2 conda-build
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  -  conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml